# -*- coding: utf-8 -*-
"""
This file simulates the heat generated by battery system in the vehicle.
"""


def Heat(current, C_b, C_c, K_ab, K_ac, K_bc, Q_btms, Q_hvac, Q_rad, Resist,
         timestep, T_a, T_b, T_c):
    """
    Reference: J.Neubauer et al. 2014. "Battery Lifetime Analysis and Simulation
    Tool (BLAST) Documentation" Equation (2.5)-(2.7).

    ===Inputs (14)===

    current: the battery current, unit: A.
    C_b: heat capacity of battery, unit: J/K.
    C_c: heat capacity of vehicle cabin, unit: J/K.
    K_ab: effective heat transfer coefficient between ambient & battery, unit: W/K.
    K_ac: effective heat transfer coefficient between ambient & cabin, unit: W/K.
    K_bc: effective heat transfer coefficient between battery & cabin, unit: W/K.
    Q_btms: heat added to or removed from the battery by the BTMS, unit: W.
    Q_hvac: heat added to or removed from the cabin by the HVAC system, unit: kW.
    Q_rad: solar irradiance, unit: kW.
    Resist: battery resistance, unit: ohm.
    timestep: time step for battery discharging (TimStp_RunOn or TimStp_RunOff), unit: sec.
    T_a: the temperature of amibient air, unit: C.
    T_b: the temperature of battery, unit: C.
    T_c: the temperature of vehicle cabin, unit: C.

    ===Outputs (2)===

    new_Tb: updated battery temperature after considering heat transfer, unit: C.
    new_Tc: updated vehicle cabin temperature after considering heat transfer, unit: C.
  
    """

    # Q_bat is the heat generation from the battery (W).
    Q_bat = current * current * Resist
    # T_b is the temperature of battery.
    new_Tb = (K_ab * (T_a - T_b) + K_bc * (T_c - T_b) + Q_btms + Q_bat) / C_b * timestep + T_b
    # T_c is the temperature of vehicle cabin.
    new_Tc = (K_ac * (T_a - T_c) + K_bc * (T_b - T_c) + (Q_rad + Q_hvac) * 1000) / C_c * timestep + T_c

    return new_Tb, new_Tc


def HeatTransfer_hvac(HVACOnOrOff, K_ac, T_a, T_c):
    """
    Reference: Neubauer et al. 2014 (doi.org/10.1016/j.jpowsour.2014.02.083) Table 1

    ===Inputs (4)===

    HVACOnOrOff: whether the HVAC system is on or off (string).
    K_ac: effective heat transfer coefficient between ambient and cabin, unit: W/K.
          It will change when the HVAC system is on. (The assumed value is based
          on [doi.org/10.1016/j.jpowsour.2014.02.083] Table 1)
    T_a: Temperature of ambient air when battery is being charged. 
         It is assumed to be fixed during charging, unit: C.
    T_c: temperature of vehicle cabin, unit: C.

    ===Outputs (1)===

    Q_hvac: heat added to or removed from the cabin by the HVAC system (kW). The
        value depends on T_c temperature. (The assumed value is based on
        [doi.org/10.1016/j.jpowsour.2014.02.083] Table 1)
    K_ac_HVAC: effective heat transfer coefficient between ambient and cabin
               after considering the HVAC system, unit: W/K.

    """

    if HVACOnOrOff != "On":
        Q_hvac = 0
        K_ac_HVAC = K_ac
    else:
        if T_c > T_a:
            K_ac_HVAC = 1500  # K_ac+1500
        else:
            K_ac_HVAC = 1500  # K_ac

        # When T_c is lower than 18.85C, heating is on.
        if T_c < 18.85:
            Q_hvac = 4.
        # When T_c is higher than 23.85C, cooling is on.
        elif T_c >= 23.88:
            Q_hvac = -4.5
        else:
            Q_hvac = -1.7 * (T_c + 273.15) + 500.4

    return Q_hvac, K_ac_HVAC


def HeatTransfer_btms(BTMSOnOrOff, f_btms, K_btms, T_b, T_low, T_up):
    """
    Reference: Neubauer et al. 2014 (doi.org/10.1016/j.jpowsour.2014.02.083) Table 3

    ===Inputs (6)===

    BTMSOnOrOff: whether the BTMS is on or off (string).
    f_btms: Coefficient of BTMS performance (ratio between BTMS heat transfer and BTMS power).
    K_btms: effective heat transfer coefficient between battery and BTMS, unit: W/K.
    T_b: temperature of battery, unit: C.
    T_low: lower temperature bondary for BTMS to work, unit: C.
    T_up: upper temperature bondary for BTMS to work, unit: C.
    
    ===Outputs===

    Q_btms: heat added to or removed from the battery by the BTMS, unit: W.

    """
    Q_btms = 0.

    # When the BTMS is on. (The assumption is based on [doi.org/10.1016/j.jpowsour.2014.02.083] Table 3)
    if BTMSOnOrOff != "Off":
        # When T_b is higher than T_up, remove extra heat from the battery.
        # And when T_b is higher than (T_up + 10 C), the removal will not change anymore.
        if T_b > T_up:
            if T_b > T_up + 10:
                Q_btms = -10 * K_btms
            else:
                Q_btms = -(T_b - T_up) * K_btms

        # When T_b is low than T_low, add extra heat to the battery.
        # And when T_b is lower than (T_low - 10 C), the added heat will not change anymore.
        elif T_b < T_low:
            if T_b < T_low - 10:
                Q_btms = 10 * K_btms
            else:
                Q_btms = (T_low - T_b) * K_btms

    # The power output for running the BTMS (kW).
    P_btms = abs(Q_btms) * f_btms / 1000

    return Q_btms, P_btms
