"""
This file contains the vehicle kninetics information and vehicle powertrain energy
efficiency information.
"""

import numpy as np


def BatPower(a_car, A_d, c_d, c_r, f_acc, f_pt_max, f_pt_min, f_rbs, grav, m_v, OCV, P_btms, Q_hvac,
             rho_air, Resist, RBSOnOrOff, sigma, theta, v_car, v_wind, P_pt_fixed):
    """
    Reference: Wikner et al. 2018. Extending Battery Lifetime by Avoiding High SOC.
    Modified to include load-dependent efficiency and fixed powertrain losses.
    ===Inputs (21)===
    a_car: vehicle acceleration, unit: m^2/s.
    A_d: front area, unit: m^2.
    c_d: coefficient of aerodynamic resistance.
    c_r: rolling resistance coefficient.
    f_acc: accessory energy efficiency (electronics etc).
    f_pt_max: powertrain efficiency at rated load (energy from bat to wheel).
    f_pt_min: powertrain efficiency at very light load.
    f_rbs: regenarative energy efficiency (stored energy/braking energy).
    grav: gravitational constant, unit: m/s^2.
    m_v: vehicle gross weight, unit: kg.
    OCV: battery open circuit voltage, unit: V.
    P_btms: power output to BTMS, unit: kW.
    Q_hvac: electric power rate of HVAC system, unit: kW.
    rho_air: air density, unit: kg/m^3.
    RBSOnOrOff: whether the regenerative braking system is on or off, string "On" or string "Off".
    Resist: battery resistance, unit: ohm.
    sigma: correction coefficient of rotational inertia.
    theta: road inclination, unit: deg.
    v_car: vehicle speend, unit: m/s.
    v_wind: wind speed, unit: m/s.
    P_pt_fixed: fixed powertrain losses (motor, inverter, control), unit: kW.
    ===Outputs (1)===
    P_bat: output, battery output power, unit: kW.

    """

    # Air drag force
    F_d = abs(0.5 * rho_air * A_d * c_d * (v_car - v_wind) ** 2)
    # Rolling resistance force
    F_r = abs(c_r * m_v * grav * np.cos(theta))
    # Grading force
    F_g = m_v * grav * np.sin(theta)
    # Acceleration force
    F_a = sigma * m_v * a_car

    # Total force
    F_total = F_d + F_r + F_g + F_a

    # Powertrain supplied power (kW).
    P_pt = F_total * v_car / 1000.

    # Electric power rate of HVAC system (kW)
    P_hvac = HVAC(Q_hvac)

    """
    When the RBS is off or vehicle speed is less than 5km/h (1.389 m/s), 
    the regenerative power would be 0. Assumed no power generated by the RBS
    when v_car <=5km/h (https://doi.org/10.1016/j.apenergy.2016.01.051).
    """
    if P_pt < 0.:
        if RBSOnOrOff != "On" or v_car < 1.389:
            P_pt = 0.
        # Regenerative power input back to the battery system (kW).
        P_bat = P_pt * f_rbs + P_hvac + P_btms
    else:
        # Power output from the battery system (kW).
        # Calculate load-dependent powertrain efficiency based on total force
        # At high load (≥1500N): f_pt = f_pt_max (0.95)
        # At very light load (≤10N): f_pt = f_pt_min (0.75)
        # Linear interpolation in between
        F_total_abs = abs(F_total)
        F_rated = 1000.0  # Rated force threshold, unit: N
        F_light = 10.0  # Light load force threshold, unit: N

        if F_total_abs >= F_rated:
            f_pt = f_pt_max
        elif F_total_abs <= F_light:
            f_pt = f_pt_min
        else:
            # Linear interpolation between light load and rated load
            f_pt = f_pt_min + (f_pt_max - f_pt_min) * (F_total_abs - F_light) / (F_rated - F_light)

        # Calculate battery power with dynamic efficiency
        if v_car > 0:
            # Add fixed losses when vehicle is moving
            P_bat = P_pt / f_acc / f_pt + P_hvac + P_btms + P_pt_fixed
        else:
            # No fixed losses when stationary
            P_bat = P_pt / f_acc / f_pt + P_hvac + P_btms

        # The limitation of power outpput from the battery system.
        temp = OCV * OCV / 4. / Resist
        P_bat = min(P_bat, temp)

    return P_bat


def HVAC(Q_hvac):
    """
    Reference: https://www.energy.gov/sites/prod/files/2014/03/f8/deer12_maranville.pdf
    ===Inputs (1)===
    Q_hvac: electric power rate of HVAC system, unit: kW.
    ===Outputs (1)===
    P_hvac: electric power rate of HVAC system (kW).

    """
    # COP = 1.5 for cooling, and COP = 2.5 for heating.
    # COP = ratio heat dissipation/electrical power intake
    if Q_hvac < 0.:
        # Cooling
        COP = 1.5  #
        P_hvac = -Q_hvac / COP
    else:
        # Heating
        COP = 2.5  #
        P_hvac = Q_hvac / COP
    return P_hvac


def DischargCurrent(OCV, P_bat, Resist):
    """
    This function aims at calculating the current when battery is discharging.

    ===Inputs (3)===
    OCV: battery open circuit voltage, unit: V.
    P_bat: this is a positive value, meaning the direction of battery power is out of the battery, unit: W.
    Resist: battery resistance, unit: ohm.
    
    ===Outputs (1)===
    current: this is a positive value, meaning the battery is discharging, unit: A.

    """
    temp = (OCV * OCV - 4 * Resist * P_bat) ** 0.5
    current1 = (OCV - temp) / 2 / Resist
    current2 = (OCV + temp) / 2 / Resist

    # Positive current value means the battery is discharging.
    if current1 <= (OCV / Resist):
        current = current1
    else:
        current = current2
    return current


def RBSCurrent(OCV, P_bat, Resist):
    """
    This function aims at caculating the current when the battery is charging (regenerative braking).

    ===Inputs===
    OCV: battery open circuit voltage, unit: V.
    P_bat: this is a negative value, meaning the direction of battery power is into the battery, unit: W.
    Resist: battery resistance, unit: ohm.
     
    ===Outputs===
    current: this is a negative value, meaning the battery is charging, unit: A.
    """
    temp = (OCV * OCV - 4 * Resist * P_bat) ** 0.5

    # Negative current value means the battery is charging.
    if temp > OCV:
        RBSCurrent = (temp - OCV) / 2 / Resist
        current = -RBSCurrent
    else:
        current = 0.

    return current
